### ISSUE TITLE
Any data in webapp

### ISSUE THREAD

**Issue by amirhosseinrajabi** [etsy/skyline#120]
Hello,
Why webapp doesn't show any data after running seed_data.py ?
"
Loading data over UDP via Horizon...
Connecting to Redis...
Congratulations! The data made it in. The Horizon pipeline seems to be working.
"

Thanks,

**Comment by danielkorczak** [comment]
seed_data.py is designed to only test horizon; it's half baked implementation should not cause anything to come up in webapp. Note: https://groups.google.com/d/msg/skyline-dev/BVAEsLtbs38/2PK3YfzLJDoJ

I do not remember the specific number off the topic of my head, but in order to get content to show up in webapp, you will need to send data in for over an hour, and make sure there is anomalous data that will trigger the algorithms. For example, send the value 150 for 80 minutes, then send 10 for the next 5 minutes, then go back to 150.

**Comment by earthgecko** [comment]
Just to clarify this issue further, metrics will only be displayed in the webapp when a metric is flagged as anomalous.  The caveat here is that analyzer will only analyse metrics only once it has the ```FULL_DURATION``` for the timeseries.  Until the ```FULL_DURATION``` timeseries are available analyzer will flag all metrics as boring and nothing will be displayed in the webapp.
